# Credenciales exclusivas para el laboratorio; no usar en producción.
apiVersion: v1
kind: Secret
metadata:
  name: tickets-db-secret
  namespace: tickets
type: Opaque
data:
  POSTGRES_USER: dGlja2V0cw==
  POSTGRES_PASSWORD: dGlja2V0cw==
  POSTGRES_DB: dGlja2V0cw==
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vdGlja2V0czp0aWNrZXRzQHBvc3RncmVzOjU0MzIvdGlja2V0cw==
